# Generated by Django 3.2.7 on 2021-12-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TechContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French')], max_length=2)),
                ('content', models.TextField()),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='transtech.techcontent')),
            ],
        ),
    ]
