# Generated by Django 3.2.7 on 2021-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0002_techcontent_techcontentversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcontentversion',
            name='status',
            field=models.CharField(choices=[('C', 'created'), ('R', 'reviewed')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techcontentversion',
            name='version_type',
            field=models.CharField(choices=[('OR', 'original'), ('TR', 'translation')], default='OR', max_length=2),
            preserve_default=False,
        ),
    ]
