# Generated by Django 3.2.7 on 2021-12-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0003_auto_20211207_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcontentversion',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('R', 'Reviewed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='techcontentversion',
            name='version_type',
            field=models.CharField(choices=[('OR', 'Original'), ('TR', 'Translation')], max_length=2),
        ),
    ]
