# Generated by Django 3.2.7 on 2021-12-12 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 9, 4, 49, 82115, tzinfo=utc)),
        ),
    ]
