# Generated by Django 3.2.7 on 2021-12-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0004_auto_20211207_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcontentversion',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('R', 'Reviewed'), ('O', 'Original version')], max_length=1),
        ),
    ]
