# Generated by Django 3.2.7 on 2021-12-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0005_alter_techcontentversion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcontentversion',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('pt', 'Portuguese'), ('zh', 'Chinese')], max_length=2),
        ),
    ]
