# Generated by Django 3.2.7 on 2021-12-12 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0005_item_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='final',
            field=models.TextField(default='this is a default value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='initial',
            field=models.TextField(default='this is a default value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='done',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
