# Generated by Django 3.2.7 on 2021-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0006_auto_20211212_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcontentversion',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('R', 'Reviewed'), ('A', 'Audited'), ('O', 'Original version')], max_length=1),
        ),
    ]
