# Generated by Django 3.2.7 on 2021-12-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secondary',
            field=models.ManyToManyField(null=True, related_name='secondary_users', to='transtech.Language'),
        ),
    ]
