# Generated by Django 3.2.7 on 2021-12-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0011_user_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locked',
            field=models.DateTimeField(blank=True),
        ),
    ]
