# Generated by Django 3.2.7 on 2021-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0014_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='A subject', max_length=64),
            preserve_default=False,
        ),
    ]
