# Generated by Django 3.2.7 on 2021-12-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transtech', '0015_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offer',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
